spring.application.name=property-service
server.port=8082
spring.data.mongodb.database=propertydb
spring.data.mongodb.uri=mongodb://localhost:27017/
server.error.include-message=always

# ?? Property type request limits (read by PropertyLimitConfig) ??
property.request.limit.hostel=50
property.request.limit.pg=30
property.request.limit.apartment=5
property.request.limit.villa=3
property.request.limit.default-limit=10
